language: python
python:
  - 2.7
install:
  - pip install sphinx
script:
  - python -m compileall -x '[.]py$' -q -f .
  - cd docs && make SPHINXOPTS="-T -W -q -j 4" html
notifications:
  email:
    on_failure: always
    on_success: change
